defaults: &defaults
  :path: '/barcelos_imports/:attachment/:attachment/:id/:style/:filename'

  :storage: s3
  :bucket: <%= ENV['S3_BUCKET_NAME'] %>
  :s3_credentials:
    :access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    :secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  :styles:
    :featured: '460x460>'
    :list: '220x220>'
    :thumb: '100x100>'

  :default_url: '/assets/missing.jpg'
  
development:
  options:
    <<: *defaults
    :whiny_thumbnails: true

production:
  options:
    <<: *defaults
